### ISSUE TITLE
composer require drupol/yaroc php-http/guzzle6-adapter installation errors

### ISSUE THREAD

**Issue by sauls** [drupol/yaroc#3]
```bash
$ composer require drupol/yaroc php-http/guzzle6-adapter
Using version ^1.0 for drupol/yaroc
Using version ^2.0 for php-http/guzzle6-adapter
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "^4.2"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - php-http/guzzle6-adapter v2.0.0 requires php-http/httplug ^2.0 -> satisfiable by php-http/httplug[v2.0.0].
    - php-http/guzzle6-adapter v2.0.1 requires php-http/httplug ^2.0 -> satisfiable by php-http/httplug[v2.0.0].
    - Conclusion: don't install php-http/httplug v2.0.0
    - Installation request for php-http/guzzle6-adapter ^2.0 -> satisfiable by php-http/guzzle6-adapter[v2.0.0, v2.0.1].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by sauls** [comment]
The only valid way to install is, to stick to older versions 😢 

```bash
$ composer require drupol/yaroc php-http/guzzle6-adapter:1.1.1
Using version ^1.0 for drupol/yaroc
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "^4.2"

Prefetching 5 packages 🎶 💨
  - Downloading (100%)

Package operations: 5 installs, 0 updates, 0 removals
  - Installing guzzlehttp/promises (v1.3.1): Loading from cache
  - Installing ralouphie/getallheaders (2.0.5): Loading from cache
  - Installing guzzlehttp/psr7 (1.5.2): Loading from cache
  - Installing guzzlehttp/guzzle (6.3.3): Loading from cache
  - Installing php-http/guzzle6-adapter (v1.1.1): Loading from cache
Writing lock file
Generating autoload files
```

**Comment by drupol** [comment]
I just pushed a new tag to fix this, can you try now ? (tag: 1.0.1)

Thanks!

**Comment by sauls** [comment]
Nope sorry. Still getting version incompability errors.

```bash
$ composer req drupol/yaroc php-http/guzzle6-adapter
Using version ^1.0 for drupol/yaroc
Using version ^2.0 for php-http/guzzle6-adapter
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "^4.2"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install drupol/yaroc 1.0.1
    - php-http/guzzle6-adapter v2.0.0 requires php-http/httplug ^2.0 -> satisfiable by php-http/httplug[v2.0.0].
    - php-http/guzzle6-adapter v2.0.1 requires php-http/httplug ^2.0 -> satisfiable by php-http/httplug[v2.0.0].
    - Can only install one of: php-http/httplug[v2.0.0, v1.1.0].
    - drupol/yaroc 1.0.0 requires php-http/httplug ^1.1 -> satisfiable by php-http/httplug[v1.1.0].
    - Installation request for drupol/yaroc ^1.0 -> satisfiable by drupol/yaroc[1.0.0, 1.0.1].
    - Installation request for php-http/guzzle6-adapter ^2.0 -> satisfiable by php-http/guzzle6-adapter[v2.0.0, v2.0.1].

Installation failed, reverting ./composer.json to its original content.
```

**Comment by drupol** [comment]
Wow... what is going on ??

**Comment by drupol** [comment]
Try to add manually the file in your composer.json, then remove the vendor and composer.lock, then do composer install.

**Comment by sauls** [comment]
Still error persists... 😢 😨 

*composer.json*
```json
{
    "require": {
        "drupol/yaroc": "^1.0",
        "php-http/guzzle6-adapter": "^2.0"
    }
}
```

*composer install (after removing composer.lock and vendors)*

```bash 
$ composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install drupol/yaroc 1.0.1
    - Conclusion: don't install drupol/yaroc 1.0.2
    - php-http/guzzle6-adapter v2.0.0 requires php-http/httplug ^2.0 -> satisfiable by php-http/httplug[v2.0.0].
    - php-http/guzzle6-adapter v2.0.1 requires php-http/httplug ^2.0 -> satisfiable by php-http/httplug[v2.0.0].
    - Can only install one of: php-http/httplug[v2.0.0, v1.1.0].
    - drupol/yaroc 1.0.0 requires php-http/httplug ^1.1 -> satisfiable by php-http/httplug[v1.1.0].
    - Installation request for drupol/yaroc ^1.0 -> satisfiable by drupol/yaroc[1.0.0, 1.0.1, 1.0.2].
    - Installation request for php-http/guzzle6-adapter ^2.0 -> satisfiable by php-http/guzzle6-adapter[v2.0.0, v2.0.1].
```

**Comment by drupol** [comment]
Try this:

```yaml
{
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require": {
        "drupol/yaroc": "^1",
        "php-http/guzzle6-adapter": "^2"
    }
}
```

**Comment by sauls** [comment]
YAY! 😃 🎆 It worked! I was missing these two lines in my composer.json file

```json
{
    "minimum-stability": "dev",
    "prefer-stable": true,
}
```

Thanks for your help!

**Comment by drupol** [comment]
Thanks :-)

To be honest, I don't know why those two lines are yet required. I have to investigate.

Have fun with yaroc and let me know how it goes!
